### ISSUE TITLE
Cardinality error 1242 / "Subquery returns more than 1 row" considered "OK" / Not throwing error

### ISSUE THREAD

**Issue by SautdeChat** [TablePlus/TablePlus#1040]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
MySQL 5.6.37

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
Version 2.0 (200)

3. The steps to reproduce this issue:
Include a subquery with multiple rows.

- Column headings are shown as if 0 rows are returned.
- Clicking "Show message" displays: "Query 1 OK: Subquery returns more than 1 row, 18446744073709551615 rows affected"
- (The too many rows thing already has an issue [here](https://github.com/TablePlus/TablePlus/issues/1031))

**Comment by huyphams** [comment]
Hi, can I have an example? 
I have fixed the bug wrong rows affected. but the bug throwing error 
`Query 1 ERROR: Subquery returns more than 1 row` seems to be ok on my setup.

**Comment by huyphams** [comment]
Btw, could you please try this build? https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks!

**Comment by SautdeChat** [comment]
Here is a simple example that should return the error:
`create table _123range (id int);`
`insert into _123range values (1), (2), (3);`
`select * from _123range;`
`select *, (select * from _123range) from _123range;`

Upgrading to 204 and testing the 205 version both do not jump to the error. The incorrect wrong count is also still present.

**Comment by huyphams** [comment]
Hi @SautdeChat thanks, I addressed that issue on this build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks again for the example.
