### ISSUE TITLE
ORA-24373 on open anywhere in Oracle 12c

### ISSUE THREAD

**Issue by raymccarthy** [TablePlus/TablePlus#1200]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):

3. The steps to reproduce this issue:

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by raymccarthy** [comment]
Oracle Drive
TablePlus 2.4(229)

1.  Connect to Oracle 12c database
2.  Press Command+P (Open anywhere)

Results
ORA-24373: invalid length specified for statement

**Comment by huyphams** [comment]
Thanks @raymccarthy I've fixed it.

**Comment by raymccarthy** [comment]
Excellent @huyphams!  I will verify in the next build.  I've also noticed some sorting issues in Oracle.  Will pay for a licence before raising any more bugs ;-)

**Comment by huyphams** [comment]
Thanks, you can download the hotfix build here: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
If you discovered any further bug, don't hesitate to report it.

**Comment by raymccarthy** [comment]
Bought the licence:-)

Downloaded the dropbox build but it still showing as 229, and I am getting the same 24373 error.

**Comment by raymccarthy** [comment]
@huyphams Sorry, forget the mention

Bought the licence:-)

Downloaded the dropbox build but it still showing as 229, and I am getting the same 24373 error.

**Comment by huyphams** [comment]
Oops sorry, I updated the wrong build, here is the correct build: https://www.dropbox.com/s/0i0ofnhi88vlxz8/TablePlus.dmg?dl=0
Thanks

**Comment by raymccarthy** [comment]
@huyphams works, now.  Thanks
