### ISSUE TITLE
Performance issues when editing 'large' blobs

### ISSUE THREAD

**Issue by jpike88** [TablePlus/TablePlus#1710]
1. Which driver are you using and version of it: mysql 3.1.0

2. Which TablePlus build number are you using: 290

3. The steps to reproduce this issue:

I have a table with a col holding mediumtext data. I have JSONs in there which can be 300kb-400kb in size. 

The right hand sidebar's preview of this shows a blank cell for the data value. This shouldn't happen, it should just show it.

When I click it, it takes over 10 seconds to show the data and locks up the window. Just interacting with it in painful. Every time I click it or press an arrow key, each operation is painfully slow.

<img width="1393" alt="Screen Shot 2020-02-09 at 10 50 01 AM" src="https://user-images.githubusercontent.com/9585787/74095902-ee2eac80-4b29-11ea-9da1-da3f3e160972.png">

**Comment by huyphams** [comment]
Thanks @jpike88 for reporting. I will try to optimize it. meanwhile, you can edit it via QuickLook, the editor in QuickLook is designed for handling large text (middle mouse or right-click Quick Look Editor). If you close the right sidebar, it would be be faster.

**Comment by huyphams** [comment]
I can reproduce it now, let me see if I can do anything to improve the performance.
<img width="1870" alt="Screen Shot 2020-02-09 at 10 59 13 AM" src="https://user-images.githubusercontent.com/3654622/74095975-38fcf400-4b2b-11ea-9b49-507344bf0b44.png">

**Comment by jpike88** [comment]
Thanks. Great product!

**Comment by huyphams** [comment]
I have got a solution and it worked. However, it needs more time to polish the details and could be delayed a little bit.

**Comment by jpike88** [comment]
That’s cool, thanks

**Comment by huyphams** [comment]
HI @jpike88 you can download this hotpatch: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0 there are still some issue and rooms for improvement but you can view and edit large blob now.

**Comment by jpike88** [comment]
Performance has massively improved, that's great.

Syntax formatting seems a little inconsistent though
![Uploading Screen Shot 2020-02-14 at 3.09.43 PM.png…]()

**Comment by huyphams** [comment]
Thank you for testing, I've fixed some bugs and added some improvements in the new build, I will upload it tonight.

**Comment by huyphams** [comment]
I've updated the new build here: https://www.dropbox.com/s/e0gew8fc0b7uam9/TablePlus.dmg?dl=0
Thank you for trying the build.

**Comment by jpike88** [comment]
This is how a JSON looks in VSCode
<img width="609" alt="Screen Shot 2020-02-15 at 1 17 57 PM" src="https://user-images.githubusercontent.com/9585787/74583043-9c889500-4ff5-11ea-8d47-e6c7032e9621.png">

TablePlus:
<img width="738" alt="Screen Shot 2020-02-15 at 1 18 15 PM" src="https://user-images.githubusercontent.com/9585787/74583047-a14d4900-4ff5-11ea-8d71-f36396987f4b.png">

Might be best to align with how VSCode chooses to highlight those tokens.

For exact hex values:

https://github.com/microsoft/vscode/blob/master/extensions/theme-defaults/themes/dark_plus.json

**Comment by huyphams** [comment]
I follow Sublime Text Highlight by it seems VScode has a better format.

**Comment by backhand** [comment]
I have the same issue on MacOS with 3.4.0 build 304. Result view is very sluggish, but right-hand preview is downright unusable - it'll beachball for 40+ secs then fire off all the click events one may or may not have queued up in exasperation.
Are there any updates in terms of a more official release?

(Btw, great product otherwise, really enjoy it after using Navicat for years)

**Comment by huyphams** [comment]
The issue is fixed in this patch @backhand https://www.dropbox.com/s/hijhy8j8b6ilpdr/TablePlus.dmg?dl=0
Thanks

**Comment by backhand** [comment]
@huyphams that's great - but is that an actual stable release? Your regular download links are in the form:
https://www.tableplus.io/release/osx/tableplus_latest
Also, this issue is not closed, which led me to believe it wasn't fixed in a stable release without presuming anything about your release cycle.

**Comment by huyphams** [comment]
actually, it was a different issue. and yes, we will release this fix on the next update, you can use the host patch above without any issue, all builds are signed by TablePlus Inc certification.
