### ISSUE TITLE
[Feature Request] Don't block UI with popups when disconnects occur

### ISSUE THREAD

**Issue by richthegeek** [TablePlus/TablePlus#2071]
Tableplus 3.8.0 (build 336).

When I'm connected to a DB and it later disconnects the modals block all UI interaction. Crucially this includes the ability to exit the program, which aside from being frustrating (I just want to quit the program please, not parse and interact with a useless disconnection message) also blocks my computer from restarting (and the disconnect happened because my terminal just quit, docker shut down, and so the DB went down).

Personally I feel the red "disconnected" bar is already plenty of warning... and I don't know enough about the UI options here to suggest alternatives.

![Screenshot 2020-09-03 at 11 28 21](https://user-images.githubusercontent.com/613900/92097626-97940300-edd8-11ea-96a0-ddeb77d27618.png)

**Comment by check24-danielpaschsannapiu** [comment]
Hey, want to add my support for this. In the age of more secure db connections through ssh tunnels this comes up a lot. 

![Image](https://github.com/user-attachments/assets/37c71d4f-4b11-4003-a240-e0e5a967456d)

I'm constantly just trying to open a new Window but am annoyed why popups telling me what I already know. 

Very common scenario:

I have 3-5 Windows open to different databases through ssh tunnels. 
Next day I open my laptop and all of them will obviously be disconnected because the ssh tunnel died. 

Just let me quickly close them. Not even CMD+Q allows me to do so. I have to manually press OK

@huyphams

**Comment by huyphams** [comment]
Hi, we fixed the issue. TablePlus now only shows a popup when the user tries to load a database, instead of coming back to the app. Also, it uses a singleton popup now (only one popup).

https://www.dropbox.com/scl/fi/mpnhecs75ruoqe3442fpa/TablePlus.dmg?rlkey=594kh1wtsg85zmqcslim6jitj&dl=0

**Comment by gempir** [comment]
I installed your DMG. 
> Version 26.8.6 (752)


I don't really see this as fixed? I repeated the scenario about a ssh tunnel. 
Detached my pc from network, left it in a meeting etc. and came back to plug it in and it tried to load my previsouly connect database. 
(I might have tapped reconnect or refreshed, not 100% sure, but that just happens out of habit)

<img width="516" height="72" alt="Image" src="https://github.com/user-attachments/assets/eb7bd13f-5495-4256-88f2-f76b791ec1b3" />

Why can't the dialogue be less aggressive? Can't it be a toast or something? A blocking modal is just so disruptive. It blocks me from closing the window. 

<img width="471" height="150" alt="Image" src="https://github.com/user-attachments/assets/ef47a362-c446-4d92-9d36-1d45df4ac62f" />

<img width="273" height="218" alt="Image" src="https://github.com/user-attachments/assets/9f2473c0-d741-4d54-b495-009486f1bf62" />

**Comment by huyphams** [comment]
I see, @gempir. I think I understand your concern about the popup not allowing us to close the application. The build above only fixed two other issues:

1. Do not show the error popup repeatedly for every workspace.
2. Only show the popup if the user has tried to interact with the app.

The popup you're seeing just by focusing the app is a bug. Did you click anything in the app, or did it happen just when you focused on TablePlus?

**Comment by gempir** [comment]
Yes it happens if I interact / click on anything in TablePlus, fair enough. I still don't like that behaviour, but I get where you are coming from there. 

But there is also this error, which just happens after some time without clicking anything

<img width="456" height="250" alt="Image" src="https://github.com/user-attachments/assets/6ea1bcf9-9440-405b-a768-e2b7c83c03b2" />

Which I then weirdly have to press "Wait" and then can close the whole Workspace. All I want always being able to fully close  a workspace. I don't want to fiddle with any popups or dialogues, just give me a Keyboard shortcut that guarantees that a workspace will be closed.
